services:
     api:
          build: ./backend
          container_name: schedulo_api
          ports:
               - "8000:8000"
          env_file:
               - ./backend/.env
          volumes:
               - ./backend:/app
          depends_on:
               - db
          environment:
               - DATABASE_URL=postgresql://schedulo_user:schedulo_password%40123@db/schedulo_db
          restart: always
     db:
          image: postgres:17
          container_name: schedulo_db
          volumes:
               - db_data:/var/lib/postgresql/data
          environment:
               POSTGRES_USER: schedulo_user
               POSTGRES_PASSWORD: schedulo_password@123
               POSTGRES_DB: schedulo_db
          restart: always
     frontend:
          build: ./frontend
          container_name: schedulo_frontend
          ports:
               - "3000:3000"
          restart: always
          depends_on:
               - api
volumes:
     db_data:
